/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrameworksIndexRouteImport } from './routes/frameworks.index'
import { Route as ControlsIndexRouteImport } from './routes/controls.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksIndexRoute = FrameworksIndexRouteImport.update({
  id: '/frameworks/',
  path: '/frameworks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsIndexRoute = ControlsIndexRouteImport.update({
  id: '/controls/',
  path: '/controls/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/controls/': typeof ControlsIndexRoute
  '/frameworks/': typeof FrameworksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/controls': typeof ControlsIndexRoute
  '/frameworks': typeof FrameworksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/controls/': typeof ControlsIndexRoute
  '/frameworks/': typeof FrameworksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/controls/' | '/frameworks/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/controls' | '/frameworks'
  id: '__root__' | '/' | '/controls/' | '/frameworks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlsIndexRoute: typeof ControlsIndexRoute
  FrameworksIndexRoute: typeof FrameworksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks/': {
      id: '/frameworks/'
      path: '/frameworks'
      fullPath: '/frameworks/'
      preLoaderRoute: typeof FrameworksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls/': {
      id: '/controls/'
      path: '/controls'
      fullPath: '/controls/'
      preLoaderRoute: typeof ControlsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlsIndexRoute: ControlsIndexRoute,
  FrameworksIndexRoute: FrameworksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
