/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as RisksIndexRouteImport } from './routes/risks.index'
import { Route as GapsIndexRouteImport } from './routes/gaps.index'
import { Route as FrameworksIndexRouteImport } from './routes/frameworks.index'
import { Route as ControlsIndexRouteImport } from './routes/controls.index'
import { Route as VendorsReviewsRouteImport } from './routes/vendors.reviews'
import { Route as VendorsDiscoveryRouteImport } from './routes/vendors.discovery'
import { Route as VendorsAllRouteImport } from './routes/vendors.all'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksIndexRoute = RisksIndexRouteImport.update({
  id: '/risks/',
  path: '/risks/',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsIndexRoute = GapsIndexRouteImport.update({
  id: '/gaps/',
  path: '/gaps/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksIndexRoute = FrameworksIndexRouteImport.update({
  id: '/frameworks/',
  path: '/frameworks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsIndexRoute = ControlsIndexRouteImport.update({
  id: '/controls/',
  path: '/controls/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsReviewsRoute = VendorsReviewsRouteImport.update({
  id: '/vendors/reviews',
  path: '/vendors/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsDiscoveryRoute = VendorsDiscoveryRouteImport.update({
  id: '/vendors/discovery',
  path: '/vendors/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsAllRoute = VendorsAllRouteImport.update({
  id: '/vendors/all',
  path: '/vendors/all',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vendors/all': typeof VendorsAllRoute
  '/vendors/discovery': typeof VendorsDiscoveryRoute
  '/vendors/reviews': typeof VendorsReviewsRoute
  '/controls/': typeof ControlsIndexRoute
  '/frameworks/': typeof FrameworksIndexRoute
  '/gaps/': typeof GapsIndexRoute
  '/risks/': typeof RisksIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vendors/all': typeof VendorsAllRoute
  '/vendors/discovery': typeof VendorsDiscoveryRoute
  '/vendors/reviews': typeof VendorsReviewsRoute
  '/controls': typeof ControlsIndexRoute
  '/frameworks': typeof FrameworksIndexRoute
  '/gaps': typeof GapsIndexRoute
  '/risks': typeof RisksIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/vendors': typeof VendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vendors/all': typeof VendorsAllRoute
  '/vendors/discovery': typeof VendorsDiscoveryRoute
  '/vendors/reviews': typeof VendorsReviewsRoute
  '/controls/': typeof ControlsIndexRoute
  '/frameworks/': typeof FrameworksIndexRoute
  '/gaps/': typeof GapsIndexRoute
  '/risks/': typeof RisksIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vendors/all'
    | '/vendors/discovery'
    | '/vendors/reviews'
    | '/controls/'
    | '/frameworks/'
    | '/gaps/'
    | '/risks/'
    | '/tasks/'
    | '/vendors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/vendors/all'
    | '/vendors/discovery'
    | '/vendors/reviews'
    | '/controls'
    | '/frameworks'
    | '/gaps'
    | '/risks'
    | '/tasks'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/vendors/all'
    | '/vendors/discovery'
    | '/vendors/reviews'
    | '/controls/'
    | '/frameworks/'
    | '/gaps/'
    | '/risks/'
    | '/tasks/'
    | '/vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VendorsAllRoute: typeof VendorsAllRoute
  VendorsDiscoveryRoute: typeof VendorsDiscoveryRoute
  VendorsReviewsRoute: typeof VendorsReviewsRoute
  ControlsIndexRoute: typeof ControlsIndexRoute
  FrameworksIndexRoute: typeof FrameworksIndexRoute
  GapsIndexRoute: typeof GapsIndexRoute
  RisksIndexRoute: typeof RisksIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks/': {
      id: '/risks/'
      path: '/risks'
      fullPath: '/risks/'
      preLoaderRoute: typeof RisksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps/': {
      id: '/gaps/'
      path: '/gaps'
      fullPath: '/gaps/'
      preLoaderRoute: typeof GapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks/': {
      id: '/frameworks/'
      path: '/frameworks'
      fullPath: '/frameworks/'
      preLoaderRoute: typeof FrameworksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls/': {
      id: '/controls/'
      path: '/controls'
      fullPath: '/controls/'
      preLoaderRoute: typeof ControlsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/reviews': {
      id: '/vendors/reviews'
      path: '/vendors/reviews'
      fullPath: '/vendors/reviews'
      preLoaderRoute: typeof VendorsReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/discovery': {
      id: '/vendors/discovery'
      path: '/vendors/discovery'
      fullPath: '/vendors/discovery'
      preLoaderRoute: typeof VendorsDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/all': {
      id: '/vendors/all'
      path: '/vendors/all'
      fullPath: '/vendors/all'
      preLoaderRoute: typeof VendorsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VendorsAllRoute: VendorsAllRoute,
  VendorsDiscoveryRoute: VendorsDiscoveryRoute,
  VendorsReviewsRoute: VendorsReviewsRoute,
  ControlsIndexRoute: ControlsIndexRoute,
  FrameworksIndexRoute: FrameworksIndexRoute,
  GapsIndexRoute: GapsIndexRoute,
  RisksIndexRoute: RisksIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
